In [3]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y = a[0].copy()
y

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[0] = 88
a

array([[[88, 88, 88],
        [88, 88, 88]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a[0] = y
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 2D array

In [9]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x.ndim

2

In [11]:
x.shape

(3, 3)

In [12]:
# access first two column
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# access first column
x[:1]

array([[1, 2, 3]])

In [14]:
# access first two column and end of two row
x[:2, 1:]

array([[2, 3],
       [5, 6]])

In [16]:
# zero assign in some element
x[:2,1:] = 0
x

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [17]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
x[:2,2]

array([3, 6])

In [19]:
x[:1,1]

array([2])

In [20]:
x[:,:1]

array([[1],
       [4],
       [7]])

In [21]:
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Boolean indexing

In [47]:
name =  np.array(['ali', 'hossein', 'maryam', 'ali'])
name

array(['ali', 'hossein', 'maryam', 'ali'], dtype='<U7')

In [48]:
name == 'ali'

array([ True, False, False,  True])

In [49]:
d = np.random.randint(0,10,(4,3))
d

array([[0, 5, 8],
       [0, 9, 2],
       [4, 0, 6],
       [5, 3, 3]])

In [50]:
# get row base on true value
d[name=='ali']

array([[0, 5, 8],
       [5, 3, 3]])

In [33]:
d[name=='ali', 1:]

array([[4, 9],
       [3, 8]])

In [34]:
d[~(name=='ali')]

array([[8, 6, 5],
       [1, 7, 6]])

In [52]:
c = name == 'ali'
c

array([ True, False, False,  True])

In [53]:
d[c]

array([[0, 5, 8],
       [5, 3, 3]])

In [54]:
d[~c]

array([[0, 9, 2],
       [4, 0, 6]])

In [56]:
mask = (name == 'ali') | (name=='maryam')
mask

array([ True, False,  True,  True])

In [57]:
d[mask]

array([[0, 5, 8],
       [4, 0, 6],
       [5, 3, 3]])

In [59]:
x = np.random.randint(-10,10,(4,3))
x

array([[ 4, -5, -5],
       [ 8, -2,  5],
       [ 9, -3,  5],
       [ 6,  6,  8]])

In [61]:
x[x<0] = 0
x

array([[4, 0, 0],
       [8, 0, 5],
       [9, 0, 5],
       [6, 6, 8]])

## Fancy indexing: indexing using integer arrays

In [67]:
y = np.empty((5,5))
for i in range(5):
    y[i] = 5*i+1
y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 6.,  6.,  6.,  6.,  6.],
       [11., 11., 11., 11., 11.],
       [16., 16., 16., 16., 16.],
       [21., 21., 21., 21., 21.]])

In [69]:
y[[0,3,4]]

array([[ 1.,  1.,  1.,  1.,  1.],
       [16., 16., 16., 16., 16.],
       [21., 21., 21., 21., 21.]])

In [70]:
y[[-1]]

array([[21., 21., 21., 21., 21.]])

In [71]:
y[[-1,-3,-5]]

array([[21., 21., 21., 21., 21.],
       [11., 11., 11., 11., 11.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [72]:
x = np.arange(35).reshape(7,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [73]:
x[[0, 3, 5],[1, 2, 4]]

array([ 1, 17, 29])

In [79]:
x[[2,6]][:,[2,4]]

array([[12, 14],
       [32, 34]])

## tansposing and swapping axes

In [80]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
x.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [82]:
# three matrix of (4,5)
y = np.arange(60).reshape((3,4,5))
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [84]:
# after swapping axes we have 4 mtrix (3,5)
y.swapaxes(0,1)

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59]]])

In [85]:
# another way for swapping axes
y.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59]]])

# Universal Function: ufunc

In [87]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [90]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [91]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [92]:
y = [1.2, -3.6, 7.8]
y

[1.2, -3.6, 7.8]

In [96]:
decimalpart, integerpart = np.modf(y)

In [97]:
integerpart

array([ 1., -3.,  7.])

In [98]:
decimalpart

array([ 0.2, -0.6,  0.8])

In [99]:
x = np.random.randn(4)
x

array([-0.95806203,  0.87169571,  0.74685958, -1.07344265])

In [100]:
y = np.random.randn(4)
y

array([-0.11611542, -0.89359601,  0.29891034, -0.71998817])

In [101]:
np.maximum(x,y)

array([-0.11611542,  0.87169571,  0.74685958, -0.71998817])

## where

In [102]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
cond = np.array([True, False, True])

In [104]:
r = [(x if c else y) for x,y,c in zip(arr1, arr2, cond) ]
r

[1, 5, 3]

In [105]:
q = np.where(cond, arr1, arr2)
q

array([1, 5, 3])

In [4]:
x = np.random.randint(-10,10,(3,3))
x

array([[-10,   7,   5],
       [  0,  -1,  -8],
       [  8,   2,   7]])

In [5]:
x > 0

array([[False,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [7]:
y = np.where( x > 0, 1, -1)
y

array([[-1,  1,  1],
       [-1, -1, -1],
       [ 1,  1,  1]])

In [8]:
z = np.where(x > 0, 1, x)
z

array([[-10,   1,   1],
       [  0,  -1,  -8],
       [  1,   1,   1]])