In [39]:
import numpy as np

# How to make array?
##
There are 6 general mechanisms for creating arrays:
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)
You can use these methods to create ndarrays or Structured arrays. This document will cover general methods for ndarray creation.

## Make 1D array

In [41]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
# dimension of array
a.ndim

1

In [45]:
# shape of array
a.shape

(3,)

In [49]:
# type of array
a.dtype

dtype('int32')

## Make 2D array

In [51]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
A.ndim

2

In [53]:
A.shape

(2, 3)

In [54]:
A.dtype

dtype('int32')

In [55]:
B = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
B

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [56]:
B.ndim

3

In [58]:
B.shape

(2, 3, 2)

## Some simple operation on array

In [63]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [64]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [65]:
a+b

array([5, 7, 9])

In [66]:
a*2

array([2, 4, 6])

In [67]:
a**2

array([1, 4, 9], dtype=int32)

In [68]:
1/a

array([1.        , 0.5       , 0.33333333])

In [69]:
a*b

array([ 4, 10, 18])

In [70]:
a+2*b

array([ 9, 12, 15])

## Compare to array

In [76]:
a = np.array([1,-3,6])
a

array([ 1, -3,  6])

In [77]:
b = np.array([4,-6,-10])
b

array([  4,  -6, -10])

In [78]:
a > b

array([False,  True,  True])