In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y = a[0].copy()
y

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a[0] = 88
a

array([[[88, 88, 88],
        [88, 88, 88]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a[0] = y
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 2D array

In [8]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x.ndim

2

In [10]:
x.shape

(3, 3)

In [11]:
# access first two column
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# access first column
x[:1]

array([[1, 2, 3]])

In [13]:
# access first two column and end of two row
x[:2, 1:]

array([[2, 3],
       [5, 6]])

In [14]:
# zero assign in some element
x[:2,1:] = 0
x

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [15]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
x[:2,2]

array([3, 6])

In [17]:
x[:1,1]

array([2])

In [18]:
x[:,:1]

array([[1],
       [4],
       [7]])

In [19]:
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Boolean indexing

In [20]:
name =  np.array(['ali', 'hossein', 'maryam', 'ali'])
name

array(['ali', 'hossein', 'maryam', 'ali'], dtype='<U7')

In [21]:
name == 'ali'

array([ True, False, False,  True])

In [22]:
d = np.random.randint(0,10,(4,3))
d

array([[8, 9, 2],
       [9, 4, 9],
       [7, 9, 6],
       [1, 3, 1]])

In [23]:
# get row base on true value
d[name=='ali']

array([[8, 9, 2],
       [1, 3, 1]])

In [24]:
d[name=='ali', 1:]

array([[9, 2],
       [3, 1]])

In [25]:
d[~(name=='ali')]

array([[9, 4, 9],
       [7, 9, 6]])

In [26]:
c = name == 'ali'
c

array([ True, False, False,  True])

In [27]:
d[c]

array([[8, 9, 2],
       [1, 3, 1]])

In [28]:
d[~c]

array([[9, 4, 9],
       [7, 9, 6]])

In [29]:
mask = (name == 'ali') | (name=='maryam')
mask

array([ True, False,  True,  True])

In [30]:
d[mask]

array([[8, 9, 2],
       [7, 9, 6],
       [1, 3, 1]])

In [31]:
x = np.random.randint(-10,10,(4,3))
x

array([[ 6,  1,  5],
       [ 8, -7, -3],
       [ 7, -4,  4],
       [-9,  8,  0]])

In [32]:
x[x<0] = 0
x

array([[6, 1, 5],
       [8, 0, 0],
       [7, 0, 4],
       [0, 8, 0]])

## Fancy indexing: indexing using integer arrays

In [33]:
y = np.empty((5,5))
for i in range(5):
    y[i] = 5*i+1
y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 6.,  6.,  6.,  6.,  6.],
       [11., 11., 11., 11., 11.],
       [16., 16., 16., 16., 16.],
       [21., 21., 21., 21., 21.]])

In [34]:
y[[0,3,4]]

array([[ 1.,  1.,  1.,  1.,  1.],
       [16., 16., 16., 16., 16.],
       [21., 21., 21., 21., 21.]])

In [35]:
y[[-1]]

array([[21., 21., 21., 21., 21.]])

In [36]:
y[[-1,-3,-5]]

array([[21., 21., 21., 21., 21.],
       [11., 11., 11., 11., 11.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [37]:
x = np.arange(35).reshape(7,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [38]:
x[[0, 3, 5],[1, 2, 4]]

array([ 1, 17, 29])

In [39]:
x[[2,6]][:,[2,4]]

array([[12, 14],
       [32, 34]])

## tansposing and swapping axes

In [40]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
x.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [42]:
# three matrix of (4,5)
y = np.arange(60).reshape((3,4,5))
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [43]:
# after swapping axes we have 4 mtrix (3,5)
y.swapaxes(0,1)

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59]]])

In [44]:
# another way for swapping axes
y.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59]]])

# Universal Function: ufunc

In [45]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [46]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [47]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [48]:
y = [1.2, -3.6, 7.8]
y

[1.2, -3.6, 7.8]

In [49]:
decimalpart, integerpart = np.modf(y)

In [50]:
integerpart

array([ 1., -3.,  7.])

In [51]:
decimalpart

array([ 0.2, -0.6,  0.8])

In [52]:
x = np.random.randn(4)
x

array([ 0.54711473,  0.53123826, -1.76848028,  0.7399813 ])

In [53]:
y = np.random.randn(4)
y

array([ 0.88817112, -0.5544984 ,  0.88839475, -0.38556654])

In [54]:
np.maximum(x,y)

array([0.88817112, 0.53123826, 0.88839475, 0.7399813 ])

## where

In [55]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
cond = np.array([True, False, True])

In [56]:
r = [(x if c else y) for x,y,c in zip(arr1, arr2, cond) ]
r

[1, 5, 3]

In [57]:
q = np.where(cond, arr1, arr2)
q

array([1, 5, 3])

In [58]:
x = np.random.randint(-10,10,(3,3))
x

array([[ 6, -3,  4],
       [ 8, -4,  3],
       [-3,  6, -1]])

In [59]:
x > 0

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True, False]])

In [60]:
y = np.where( x > 0, 1, -1)
y

array([[ 1, -1,  1],
       [ 1, -1,  1],
       [-1,  1, -1]])

In [61]:
z = np.where(x > 0, 1, x)
z

array([[ 1, -3,  1],
       [ 1, -4,  1],
       [-3,  1, -1]])

In [63]:
score = np.random.randint(0,20,(3,4))
score

array([[15,  2, 19, 14],
       [17,  2,  1, 16],
       [19,  6,  6,  8]])

In [64]:
np.where(score > 10, score, 10)

array([[15, 10, 19, 14],
       [17, 10, 10, 16],
       [19, 10, 10, 10]])

In [67]:
x = [[1, 2],[3, 4]]
y = [[5, 6],[7, 8]]
c = [[True, False],[False, True]]
np.where(c, x, y)

array([[1, 6],
       [7, 4]])

## Mathematical and Statistical Methods

In [68]:
x = np.array([[7, 8, -2, 4, 3, 3, 1]])
x

array([[ 7,  8, -2,  4,  3,  3,  1]])

In [69]:
np.amin(x) # minmum

-2

In [70]:
np.amax(x) # maximum

8

In [71]:
np.mean(x) # mean

3.4285714285714284

In [72]:
np.var(x) # variance

9.959183673469386

In [73]:
np.std(x) # standard deviation

3.155817433482074

In [74]:
np.median(x) # median

3.0

In [75]:
np.sort(x) # sort

array([[-2,  1,  3,  3,  4,  7,  8]])

In [76]:
np.quantile(x, 0.25)

2.0

In [77]:
np.quantile(x, 0.5)

3.0

In [78]:
np.quantile(x,0.75)

5.5

In [80]:
np.quantile(x,1)

8

In [86]:
np.percentile(x,25) # 25 percemt of data iss less than 2.0

2.0

In [87]:
np.percentile(x,50) # 50 percemt of data iss less than 3.0

3.0

In [88]:
np.percentile(x,75) # 75 percemt of data iss less than 5.5

5.5

In [89]:
np.percentile(x,100)

8.0

In [90]:
np.percentile(x,10) # 10 percent of data is less than -0.199...

-0.19999999999999973

In [95]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
x

array([1, 2, 3, 4, 5, 6, 7])

In [96]:
np.sum(x)

28

In [97]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [98]:
np.prod(x)

5040

In [99]:
np.cumprod(x)

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

In [101]:
y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.sum(y, axis=0) # row sumation

array([12, 15, 18])

In [104]:
np.cumsum(y, axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [103]:
np.sum(y, axis=1) # column sumation

array([ 6, 15, 24])

In [105]:
np.cumsum(y, axis=1) # column sumation

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

## all, any

In [106]:
a = np.array([True, False, True])
a

array([ True, False,  True])

In [108]:
a.any() # at least one of them is True

True

In [110]:
a.all() # if all is True

False

In [112]:
b = [0, 2, -3]

In [113]:
# 0 ---> False
np.any(b) # if at least is none of zero

True

In [115]:
np.all(b) # if all is none of zero

False

In [116]:
c = [8, 2, -3]
c

[8, 2, -3]

In [117]:
np.all(c)

True

# unique

In [118]:
z = np.array([3, 4, 7, 4, 2, 1, 3, 5])
z

array([3, 4, 7, 4, 2, 1, 3, 5])

In [119]:
np.unique(z)

array([1, 2, 3, 4, 5, 7])

In [120]:
a, i = np.unique(z, return_index=True)

In [121]:
a

array([1, 2, 3, 4, 5, 7])

In [122]:
i

array([5, 4, 0, 1, 7, 2], dtype=int64)

## sort

In [123]:
data = [[('shahriar', 18.5, 19 ), ('Hossein', 15.25, '52'), ('maryam', 13.75, 50)]]
data

[[('shahriar', 18.5, 19), ('Hossein', 15.25, '52'), ('maryam', 13.75, 50)]]

In [124]:
type(data)

list

In [126]:
d = [('name', 'S10'), ('score', float), ('age', int)]
d

[('name', 'S10'), ('score', float), ('age', int)]

In [131]:
arr = np.array(data, dtype=d)

In [133]:
np.sort(arr, order='score')

array([[(b'maryam', 13.75, 50), (b'Hossein', 15.25, 52),
        (b'shahriar', 18.5 , 19)]],
      dtype=[('name', 'S10'), ('score', '<f8'), ('age', '<i4')])

In [134]:
np.sort(arr, order='age')

array([[(b'shahriar', 18.5 , 19), (b'maryam', 13.75, 50),
        (b'Hossein', 15.25, 52)]],
      dtype=[('name', 'S10'), ('score', '<f8'), ('age', '<i4')])

## in1d

In [135]:
# checking one of array element in other array

In [142]:
x = np.array([7, 1, 4, 2, 5, 7])
y = np.array([3, 4, 7])
np.in1d(x,y)

array([ True, False,  True, False, False,  True])

In [143]:
x = np.array([7, 1, 4, 2, 5, 7])
y = np.array([3, 4, 7])
m = np.in1d(x,y)
x[m]

array([7, 4, 7])

In [144]:
m = np.in1d(x,y, invert=True)
x[m]

array([1, 2, 5])