In [ ]:
import numpy as np

: 

### Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [3]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [5]:
b = np.zeros([3,4])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b = np.zeros([3,3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b = np.full(3,2)
b

array([2, 2, 2])

In [9]:
b = np.full([2,2],10)
b

array([[10, 10],
       [10, 10]])

In [10]:
b = np.full((2,2),5)
b

array([[5, 5],
       [5, 5]])

In [12]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [13]:
c = np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
lst = [1,2]
a = np.array(lst, dtype=np.int32)
a.dtype

dtype('int32')

In [16]:
lst = [1,2]
b = np.array(lst, dtype=np.float64)
b.dtype

dtype('float64')

In [17]:
b

array([1., 2.])

In [18]:
a.dtype

dtype('int32')

In [19]:
a.astype(np.float64)

array([1., 2.])

In [20]:
lst = [1.2, 3.4]
a = np.array(lst)
a

array([1.2, 3.4])

In [21]:
a.dtype

dtype('float64')

In [22]:
a.astype(np.int32)

array([1, 3])

## indexing and slicing

In [23]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
a[3]

3

In [25]:
a[2:5]

array([2, 3, 4])

In [28]:
a[2:5] = 6
a

array([0, 1, 6, 6, 6, 5, 6, 7])

In [30]:
x = a[3:6]
x

array([6, 6, 5])

In [31]:
x[1] = 17
x

array([ 6, 17,  5])

In [32]:
a

array([ 0,  1,  6,  6, 17,  5,  6,  7])

In [34]:
x[:] = 64
x

array([64, 64, 64])

In [35]:
a

array([ 0,  1,  6, 64, 64, 64,  6,  7])

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[2:6].copy()

array([2, 3, 4, 5])

In [39]:
x = a[2:6].copy()
x

array([2, 3, 4, 5])

In [41]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a[0]

array([1, 2, 3])

In [43]:
a[0][2]

3

In [44]:
a[0,2]

3

In [46]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
a.ndim

3

In [49]:
a.shape

(2, 2, 3)

In [50]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a[0][1]

array([4, 5, 6])

In [52]:
a[0][1][2]

6